<?php

declare(strict_types=1);

namespace Semitexa\Docs\Application\Service;

use Semitexa\Core\Attribute\AsService;

/**
 * Checks what the documentation asserts against what the framework has.
 *
 * A page makes claims a machine can settle: `#[AsPublicPayload]` is an
 * attribute, `bin/semitexa ai:verify` is a command, `SWOOLE_PORT` is a key the
 * code reads. This finds those claims and looks each one up in the truth index.
 *
 * The hard part is not finding claims — it is not inventing them. An earlier
 * pass counted `MODULE_STRUCTURE` and `ADDING_ROUTES` as unknown environment
 * variables and reported an 82% failure rate; they are documentation filenames.
 * A linter that cries wolf gets muted, so every extractor here is deliberately
 * narrower than it could be, and anything that cannot be settled confidently is
 * left alone rather than guessed at.
 */
#[AsService]
final class DocumentationClaimLinter
{
    public const ARTIFACT = 'semitexa.docs.lint/v1';

    /** Placed on, or directly above, a line whose claim is deliberate. */
    public const IGNORE_MARKER = '<!-- docs-lint-ignore -->';

    /**
     * Anywhere in a file whose subject is something that does not exist.
     * A proposal names unbuilt API in every other paragraph; marking each line
     * would bury the document in scaffolding.
     */
    public const IGNORE_FILE_MARKER = '<!-- docs-lint-ignore-file -->';

    /**
     * Generated reference is verified by `docs:reference:generate --check`.
     *
     * Claim linting it as authored prose produces false failures whenever a
     * consumer intentionally does not install the package that owns a command.
     */
    private const GENERATED_REFERENCE_MARKER = '<!-- Generated by `bin/semitexa docs:reference:generate`';

    /**
     * Suggest a rename only when the names are close enough to be the same idea.
     * Edit distance is the wrong ruler here: `AsPayload` became
     * `AsPublicPayload`, six edits apart but obviously the same thing, while six
     * edits also separates plenty of unrelated names. Character overlap tracks
     * what a rename actually does — keep the word, qualify it.
     */
    private const SUGGESTION_MIN_SIMILARITY = 68.0;

    /**
     * @param array<string, mixed> $index
     * @param list<string>         $roots
     * @param string|null          $instructionsRoot the project root, to read the corpus as instructions
     *                                               to an agent as well (see instructionClaims())
     *
     * @return array<string, mixed>
     */
    public function lint(array $index, array $roots, ?string $instructionsRoot = null): array
    {
        $known = $this->knownSurface($index);
        $namespaces = array_fill_keys(array_map(
            static fn (string $command): string => explode(':', $command)[0],
            $known['command'],
        ), true);
        $installedRelease = is_string($index['release_version'] ?? null) ? $index['release_version'] : null;
        $findings = [];
        $filesScanned = 0;

        foreach ($this->markdownFiles($roots) as $path) {
            $filesScanned++;
            $body = @file_get_contents($path);
            if ($body === false) {
                // A gate that could not read a file must not pass it.
                throw new \RuntimeException(sprintf('Cannot read documentation file "%s".', $path));
            }
            // An exempt page is exempt from every check, release provenance
            // included: generated reference carries whatever release the
            // generator could resolve, and a proposal is not a claim at all.
            if (
                str_contains($body, self::IGNORE_FILE_MARKER)
                || str_contains($body, self::GENERATED_REFERENCE_MARKER)
            ) {
                continue;
            }

            $releaseFinding = $this->releaseMetadataFinding($body, $path, $installedRelease);
            if ($releaseFinding !== null) {
                $findings[] = $releaseFinding;
            }

            $lines = preg_split('/\R/', $body) ?: [];
            $claims = $this->claims($lines);
            if ($instructionsRoot !== null && str_contains($path, '/skills/')) {
                // A skill drives shell scripts: its `KEY=value` lines are their
                // environment (RELEASE_CHANNEL), which no PHP code reads.
                $claims = array_values(array_filter($claims, static fn (array $claim): bool => $claim['kind'] !== 'env'));
            }
            if ($instructionsRoot !== null) {
                foreach ($this->instructionClaims($lines) as $claim) {
                    if ($claim['kind'] === 'path') {
                        if (!$this->pathExists($claim['value'], ($claim['from'] ?? 'root') === 'file' ? dirname($path) : $instructionsRoot, $instructionsRoot)) {
                            $findings[] = ['file' => $path, 'line' => $claim['line'], 'kind' => 'path', 'claim' => $claim['value'], 'suggestion' => null];
                        }
                        continue;
                    }
                    // A bare `x:y` is a command only in a namespace commands use:
                    // `skill_copies:project` is a verify target id, not something to run.
                    if (isset($namespaces[explode(':', $claim['value'])[0]])) {
                        $claims[] = $claim;
                    }
                }
            }

            foreach ($claims as $claim) {
                $names = $known[$claim['kind']] ?? [];
                if (in_array($claim['value'], $names, true)) {
                    continue;
                }

                // `#[InjectAs*]` is one claim about three attributes, not a
                // claim about an attribute called "InjectAs".
                if (str_ends_with($claim['value'], '*')) {
                    $prefix = rtrim($claim['value'], '*');
                    foreach ($names as $name) {
                        if ($prefix !== '' && str_starts_with($name, $prefix)) {
                            continue 2;
                        }
                    }
                }

                if ($claim['kind'] === 'env' && $this->matchesPattern($claim['value'], $known['env_pattern'] ?? [])) {
                    continue;
                }

                $findings[] = [
                    'file' => $path,
                    'line' => $claim['line'],
                    'kind' => $claim['kind'],
                    'claim' => $claim['value'],
                    'suggestion' => $this->closest(
                        $claim['value'],
                        $known[$claim['kind'] . '_own'] ?? $names,
                    ),
                ];
            }
        }

        usort($findings, static function (array $a, array $b): int {
            return [$a['file'], $a['line']] <=> [$b['file'], $b['line']];
        });

        return [
            'artifact' => self::ARTIFACT,
            'files_scanned' => $filesScanned,
            'kinds_checked' => $instructionsRoot === null ? ['attribute', 'command', 'env key'] : ['attribute', 'command', 'env key', 'file path'],
            'findings' => $findings,
            'by_kind' => $this->countByKind($findings),
        ];
    }

    /**
     * @return array{file: string, line: int, kind: string, claim: string, suggestion: ?string}|null
     */
    private function releaseMetadataFinding(string $body, string $path, ?string $installedRelease): ?array
    {
        if (preg_match('/\A---\R(.*?)\R---\R/s', $body, $frontMatter) !== 1) {
            return null;
        }

        // The front-matter parser unquotes scalars, so `status: "published"`
        // is the same page as `status: published`. A gate that only sees one
        // spelling silently exempts the other.
        if (preg_match('/^status:\s*["\']?(canonical|published)["\']?\s*$/mi', $frontMatter[1]) !== 1) {
            return null;
        }

        if (preg_match('/^verified_against:\s*["\']?([^"\'\s]+)["\']?\s*$/mi', $frontMatter[1], $verified, PREG_OFFSET_CAPTURE) !== 1) {
            return [
                'file' => $path,
                'line' => 1,
                'kind' => 'release_metadata',
                'claim' => 'verified_against',
                'suggestion' => $installedRelease,
            ];
        }

        $version = $verified[1][0];
        $line = substr_count(substr($frontMatter[1], 0, $verified[0][1]), "\n") + 2;
        if (preg_match('/^\d{4}\.\d{2}\.\d{2}\.\d{4}$/', $version) !== 1) {
            return [
                'file' => $path,
                'line' => $line,
                'kind' => 'release_metadata',
                'claim' => $version,
                'suggestion' => $installedRelease,
            ];
        }

        if (
            $installedRelease !== null
            && preg_match('/^\d{4}\.\d{2}\.\d{2}\.\d{4}$/', $installedRelease) === 1
            && strcmp($version, $installedRelease) > 0
        ) {
            return [
                'file' => $path,
                'line' => $line,
                'kind' => 'release_version',
                'claim' => $version,
                'suggestion' => $installedRelease,
            ];
        }

        return null;
    }

    /**
     * @param array<string, mixed> $index
     *
     * @return array<string, list<string>>
     */
    private function knownSurface(array $index): array
    {
        /** @var list<array{name?: string}> $attributes */
        $attributes = $index['attributes'] ?? [];
        /** @var list<array{name?: string}> $commands */
        $commands = $index['commands'] ?? [];

        // A page may legitimately show an attribute from another library. Those
        // are known names too — just not Semitexa's — and flagging them would
        // make the report untrustworthy exactly where it should be sharpest.
        /** @var list<string> $foreign */
        $foreign = (array) ($index['foreign_attributes'] ?? []);

        return [
            'attribute' => array_values(array_unique(array_merge(
                array_values(array_filter(array_column($attributes, 'name'))),
                $foreign,
            ))),
            // Foreign names are valid to mention but never worth recommending:
            // suggesting PHPUnit's RequiresPhp for RequiresAuth is noise.
            'attribute_own' => array_values(array_filter(array_column($attributes, 'name'))),
            'command' => array_values(array_filter(array_column($commands, 'name'))),
            'env' => array_values((array) ($index['env_keys'] ?? [])),
            'env_pattern' => array_values((array) ($index['env_key_patterns'] ?? [])),
        ];
    }

    /**
     * Claims worth checking, with the line they were made on.
     *
     * Deliberately absent: Twig calls and application class names. Pages show
     * plenty of both as illustrations of code a reader is about to write, and a
     * checker cannot tell an example apart from a reference to something that
     * should exist. Reporting those would be guessing with a straight face.
     *
     * @param list<string> $lines
     *
     * @return list<array{kind: string, value: string, line: int}>
     */
    private function claims(array $lines): array
    {
        $claims = [];
        $inFence = false;
        $inHistory = false;
        $fenceIgnored = false;
        $pendingIgnore = false;

        foreach ($lines as $offset => $line) {
            $marked = str_contains($line, self::IGNORE_MARKER);

            if (preg_match('/^\s*```/', $line) === 1) {
                if (!$inFence) {
                    // A marker on the line above covers the whole block, not
                    // just its first line: a migration step that greps for the
                    // old attribute names is one instruction, not five claims.
                    $fenceIgnored = $pendingIgnore || $marked;
                }

                $inFence = !$inFence;
                $pendingIgnore = false;

                continue;
            }

            if (!$inFence && preg_match('/^#{1,6}\s+(.*)$/', $line, $heading) === 1) {
                // A "Before" section exists to name the API you are migrating
                // from. Reporting it would mean a migration guide can never be
                // written without failing the build.
                $inHistory = preg_match(
                    '/^(before|old|legacy|deprecated|removed|previously)\b/i',
                    trim($heading[1]),
                ) === 1;
                $pendingIgnore = false;

                continue;
            }

            $ignored = $inHistory
                || ($inFence && $fenceIgnored)
                || $marked
                || $pendingIgnore;

            // The marker carries to the next line so it can sit above the thing
            // it excuses rather than trailing it.
            $pendingIgnore = $marked;

            if ($ignored) {
                continue;
            }

            $number = $offset + 1;

            // Fenced blocks are checked for attributes and commands — they hold
            // most such mentions, and a fenced example is precisely what a
            // reader copies. They are *not* checked for env keys: a shell or PHP
            // block is full of assignments that are not environment at all.
            foreach ($this->matches('/#\[([A-Z][A-Za-z0-9]*\*?)/', $line) as $value) {
                $claims[] = ['kind' => 'attribute', 'value' => $value, 'line' => $number];
            }

            foreach ($this->matches('/(?:bin\/)?semitexa\s+([a-z][a-z0-9]*:[a-z0-9:_-]+)/', $line) as $value) {
                $claims[] = ['kind' => 'command', 'value' => rtrim($value, ':'), 'line' => $number];
            }

            // Only an assignment is unambiguous. `FOO=bar` is someone writing an
            // environment variable down; a bare capitalised token in prose is
            // just as likely to be a filename, a constant or an acronym.
            if (!$inFence) {
                foreach ($this->matches('/^\s*(?:[-*]\s*)?`?([A-Z][A-Z0-9_]{2,})`?\s*=/', $line) as $value) {
                    $claims[] = ['kind' => 'env', 'value' => $value, 'line' => $number];
                }
            }
        }

        return $claims;
    }

    /**
     * The claims an instruction file makes that a docs page does not.
     *
     * Instructions to an agent (AGENTS.md, CLAUDE.md, AI_NOTES.md, a skill) are
     * read to be acted on: a command named there gets run, a file named there
     * gets opened. So beyond what claims() checks, they are held to two more:
     *
     *  - a command in backticks without the `semitexa` prefix, `ai:orient` in a
     *    table cell. Only in namespaces commands use (lint() checks); a pattern
     *    such as `ai:review-graph:*` is a family, not a name.
     *  - a file path: in backticks from the project root (`packages/...`,
     *    `src/...`), or a relative markdown link. A placeholder (an ellipsis,
     *    `{Name}`, `<id>`, `*`) is a shape, not a file; var/ and vendor/ are not
     *    the project's own to promise.
     *
     * Fenced blocks are left alone: a shell example writes paths as often as
     * it reads them.
     *
     * MEASURED 2026-10-03 on this workspace's root instructions and skills
     * (18 files): 196 command and 45 path claims, every one live once
     * placeholders and the wrapper's own commands were told apart. Class names
     * were considered and dropped: the corpus names none in a checkable form.
     *
     * @param list<string> $lines
     *
     * @return list<array{kind: string, value: string, line: int, from?: string}>
     */
    private function instructionClaims(array $lines): array
    {
        $claims = [];
        // The opening fence, `` ``` `` or `~~~` of some length: only the same
        // character, at least as long, closes it (CommonMark).
        $fence = null;
        $pendingIgnore = false;
        foreach ($lines as $offset => $line) {
            if (preg_match('/^\s*(`{3,}|~{3,})/', $line, $marker) === 1) {
                if ($fence === null) {
                    $fence = $marker[1];
                    continue;
                }
                if ($marker[1][0] === $fence[0] && strlen($marker[1]) >= strlen($fence) && trim(substr(ltrim($line), strlen($marker[1]))) === '') {
                    $fence = null;
                    continue;
                }
            }
            $marked = str_contains($line, self::IGNORE_MARKER);
            $ignored = $fence !== null || $marked || $pendingIgnore;
            $pendingIgnore = $marked;
            if ($ignored) {
                continue;
            }
            $number = $offset + 1;
            foreach ($this->matches('/`(?:bin\/semitexa\s+)?([a-z][a-z0-9-]*(?::[a-z0-9-]+)+)(?=[`\s])/', $line) as $value) {
                $claims[] = ['kind' => 'command', 'value' => $value, 'line' => $number];
            }
            foreach ($this->matches('/`((?:packages|src|bin|config|tests|resources|docs|\.claude)\/[^`\s]+)`/', $line) as $value) {
                $claims[] = ['kind' => 'path', 'value' => $value, 'line' => $number, 'from' => 'root'];
            }
            // A link is read by whoever follows it from the file it is in.
            foreach ($this->matches('/\]\((?![a-z]+:|#|\/)([^)\s#]+)(?:#[^)]*)?\)/', $line) as $value) {
                $claims[] = ['kind' => 'path', 'value' => $value, 'line' => $number, 'from' => 'file'];
            }
        }

        return array_values(array_filter(
            $claims,
            static fn (array $claim): bool => $claim['kind'] !== 'path' || preg_match('/\.\.\.|\x{2026}|[{}<>*$]/u', $claim['value']) !== 1,
        ));
    }

    /**
     * Resolved from one base only: the project root for a root-anchored path,
     * the linking file's directory for a link. Trying both let a broken link
     * pass on a file of the same name at the root (review of docs#87).
     *
     * A scaffold doc names a framework file by its workspace path,
     * `packages/semitexa-docs/...`; a consumer project has the same file at
     * `vendor/semitexa/docs/...`, and it is not missing there.
     */
    private function pathExists(string $value, string $base, string $projectRoot): bool
    {
        $value = rtrim($value, '/.,;:');
        $candidate = rtrim($base, '/') . '/' . $value;
        if (file_exists($candidate)) {
            return true;
        }
        $root = rtrim($projectRoot, '/') . '/';
        if (!str_starts_with($candidate, $root)) {
            return false;
        }
        $relative = substr($candidate, strlen($root));
        $installed = preg_replace('#^packages/semitexa-([a-z0-9-]+)/#', 'vendor/semitexa/$1/', $relative) ?? $relative;

        return $installed !== $relative && file_exists($root . $installed);
    }

    /**
     * Some keys are never written down: the code composes
     * `TENANT_{$id}_DOMAIN`, so only the shape can be known.
     *
     * @param list<string> $patterns
     */
    private function matchesPattern(string $value, array $patterns): bool
    {
        foreach ($patterns as $pattern) {
            $regex = '/^' . str_replace('\*', '[A-Z0-9_]+', preg_quote($pattern, '/')) . '$/';
            if (preg_match($regex, $value) === 1) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return list<string>
     */
    private function matches(string $pattern, string $subject): array
    {
        preg_match_all($pattern, $subject, $found);

        return array_values(array_unique($found[1] ?? []));
    }

    /**
     * The nearest real name, when one is near enough to be the same idea under a
     * different spelling — which is what a rename leaves behind.
     *
     * @param list<string> $candidates
     */
    private function closest(string $value, array $candidates): ?string
    {
        $best = null;
        $bestSimilarity = 0.0;

        foreach ($candidates as $candidate) {
            similar_text($value, $candidate, $percent);
            if ($percent > $bestSimilarity) {
                $bestSimilarity = $percent;
                $best = $candidate;
            }
        }

        return $bestSimilarity >= self::SUGGESTION_MIN_SIMILARITY ? $best : null;
    }

    /**
     * @param list<array{kind: string}> $findings
     *
     * @return array<string, int>
     */
    private function countByKind(array $findings): array
    {
        $counts = [];
        foreach ($findings as $finding) {
            $counts[$finding['kind']] = ($counts[$finding['kind']] ?? 0) + 1;
        }

        ksort($counts);

        return $counts;
    }

    /**
     * @param list<string> $roots
     *
     * @return list<string>
     */
    private function markdownFiles(array $roots): array
    {
        $files = [];

        foreach ($roots as $root) {
            if (is_file($root)) {
                $files[] = $root;
                continue;
            }

            if (!is_dir($root)) {
                continue;
            }

            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS),
                \RecursiveIteratorIterator::LEAVES_ONLY,
            );

            foreach ($iterator as $file) {
                if ($file instanceof \SplFileInfo && strtolower($file->getExtension()) === 'md') {
                    $files[] = $file->getPathname();
                }
            }
        }

        sort($files);

        return array_values(array_unique($files));
    }

    /**
     * A finding's identity for baseline purposes: the claim and where it lives,
     * but not the line it sits on, so that editing the prose above a known
     * problem does not resurrect it as new.
     *
     * @param array{file: string, kind: string, claim: string} $finding
     */
    public function fingerprint(array $finding, string $relativeTo = ''): string
    {
        return $finding['kind'] . ':' . $finding['claim'] . '@' . $this->documentPath((string) $finding['file']);
    }

    /**
     * The path from the corpus root, not from the project root.
     *
     * The same page is `packages/semitexa-docs/docs/en/x.md` in the monorepo and
     * `vendor/semitexa/docs/docs/en/x.md` in a consumer project. Keying a
     * baseline on the project-relative path means it silently stops matching
     * when the corpus is read from the other one — which is how a recorded
     * baseline came back reporting every finding it was meant to hold.
     */
    private function documentPath(string $file): string
    {
        foreach (['/docs/docs/', '/docs/'] as $marker) {
            $at = strrpos($file, $marker);
            if ($at !== false) {
                return ltrim(substr($file, $at + strlen($marker)), '/');
            }
        }

        return ltrim($file, '/');
    }
}
