<?php

declare(strict_types=1);

namespace Semitexa\Docs\Application\Service;

use Semitexa\Core\Attribute\AsService;
use Semitexa\Core\Support\ProjectRoot;

/**
 * Writes the reference section from the truth index.
 *
 * The inventory counted 422 public surface items and found 255 of them named
 * nowhere. Hand-writing that is not a plan — and hand-written reference is the
 * kind that rots first, because a signature changes without anyone thinking of
 * the page. So the half of documentation that is pure fact is produced from the
 * code, and the half that requires judgement stays hand-written elsewhere.
 *
 * The examples are harvested, never invented: for each attribute the generator
 * finds a real usage in the codebase and quotes it with its file. An invented
 * example is a claim nobody checked; a quoted one fails visibly when the code
 * moves on.
 */
#[AsService]
final class ReferenceGenerator
{
    private const PROVENANCE = 'Generated by `bin/semitexa docs:reference:generate` — do not edit by hand.';

    /**
     * The example applications teach better than framework internals, so a
     * usage from one of these wins. They are ordinary installed packages, which
     * matters: the output has to be a function of released code, not of which
     * repositories happen to be checked out beside it.
     */
    private const EXAMPLE_PACKAGES = ['demo', 'platform-site', 'site', 'os-site'];

    /**
     * @param array<string, mixed> $index
     *
     * @return array<string, string> relative path => file contents
     */
    public function generate(array $index): array
    {
        $usages = $this->harvestAttributeUsages($index);

        $files = [];
        foreach ($this->attributesByPackage($index) as $package => $attributes) {
            $files['reference/attributes-' . $this->slug($package) . '.md']
                = $this->attributePage($package, $attributes, $usages);
        }

        foreach ($this->commandsByNamespace($index) as $namespace => $commands) {
            $files['reference/commands-' . $this->slug($namespace) . '.md']
                = $this->commandPage($namespace, $commands);
        }

        $events = $index['events'] ?? [];
        if ($events !== []) {
            $files['reference/events.md'] = $this->eventPage($events);
        }

        $files['reference/README.md'] = $this->indexPage($files, $index);

        return $files;
    }

    /**
     * @param array<string, mixed> $index
     *
     * @return array<string, list<array<string, mixed>>>
     */
    private function attributesByPackage(array $index): array
    {
        $grouped = [];
        foreach ($index['attributes'] ?? [] as $attribute) {
            $parts = explode('\\', (string) $attribute['fqcn']);
            $grouped[$parts[1] ?? 'Other'][] = $attribute;
        }

        ksort($grouped);

        return $grouped;
    }

    /**
     * @param array<string, mixed> $index
     *
     * @return array<string, list<array<string, mixed>>>
     */
    private function commandsByNamespace(array $index): array
    {
        $grouped = [];
        foreach ($index['commands'] ?? [] as $command) {
            $name = (string) $command['name'];
            $grouped[str_contains($name, ':') ? explode(':', $name)[0] : 'general'][] = $command;
        }

        ksort($grouped);

        return $grouped;
    }

    /**
     * One real usage per attribute, quoted from the codebase.
     *
     * @param array<string, mixed> $index
     *
     * @return array<string, array{file: string, snippet: string}>
     */
    private function harvestAttributeUsages(array $index): array
    {
        $names = [];
        foreach ($index['attributes'] ?? [] as $attribute) {
            $names[(string) $attribute['name']] = true;
        }

        $found = [];
        foreach ($this->sourceFiles() as $path => $relative) {
            $body = (string) file_get_contents($path);
            if (!str_contains($body, '#[')) {
                continue;
            }

            $lines = preg_split('/\R/', $body) ?: [];
            foreach ($lines as $offset => $line) {
                if (preg_match('/^\s*#\[([A-Z][A-Za-z0-9]*)\s*[(\]]/', $line, $match) !== 1) {
                    continue;
                }

                $name = $match[1];
                if (!isset($names[$name])) {
                    continue;
                }

                $better = !isset($found[$name]) || $this->isBetterExample($relative, $found[$name]['file']);
                if (!$better) {
                    continue;
                }

                $found[$name] = [
                    'file' => $relative,
                    'snippet' => $this->snippet($lines, $offset),
                ];
            }
        }

        return $found;
    }

    /**
     * The attribute line plus the declaration it sits on — enough to see what it
     * attaches to, without pasting a class.
     *
     * @param list<string> $lines
     */
    private function snippet(array $lines, int $offset): string
    {
        $snippet = [];
        $depth = 0;
        $attributeClosed = false;

        for ($i = $offset, $max = min($offset + 24, count($lines) - 1); $i <= $max; $i++) {
            $line = rtrim($lines[$i]);

            if (!$attributeClosed) {
                // An attribute may span lines. Cutting it at an arbitrary line
                // count produces a sample that does not parse, which is exactly
                // what a reader would copy.
                $depth += substr_count($line, '[') - substr_count($line, ']');
                $snippet[] = $line;
                if ($depth <= 0) {
                    $attributeClosed = true;
                }

                continue;
            }

            if (trim($line) === '') {
                continue;
            }

            $snippet[] = $line;

            // Stacked attributes above the declaration are part of the picture;
            // stop once the thing being decorated has been shown.
            if (preg_match('/^\s*#\[/', $line) === 1) {
                $depth = substr_count($line, '[') - substr_count($line, ']');
                $attributeClosed = $depth <= 0;

                continue;
            }

            break;
        }

        return implode("\n", $snippet);
    }

    /**
     * Deterministic: better rank wins, and equal ranks fall back to path order
     * so the same installation always produces the same page. Without the
     * tie-break, --check reports drift that is only filesystem iteration order.
     */
    private function isBetterExample(string $candidate, string $current): bool
    {
        $candidateRank = $this->exampleRank($candidate);
        $currentRank = $this->exampleRank($current);

        return $candidateRank === $currentRank
            ? strcmp($candidate, $current) < 0
            : $candidateRank < $currentRank;
    }

    private function exampleRank(string $relative): int
    {
        foreach (self::EXAMPLE_PACKAGES as $index => $package) {
            if (str_starts_with($relative, 'vendor/semitexa/' . $package . '/')) {
                return $index;
            }
        }

        return count(self::EXAMPLE_PACKAGES);
    }

    /**
     * @return iterable<string, string> absolute path => project-relative path
     */
    private function sourceFiles(): iterable
    {
        $root = ProjectRoot::get();

        foreach (['vendor/semitexa'] as $dir) {
            $base = $root . '/' . $dir;
            if (!is_dir($base)) {
                continue;
            }

            // Follow symlinks: a path-repo install links vendor/semitexa/demo to a
            // sibling checkout, and skipping those would make the examples
            // depend on how the project happens to be wired rather than on what
            // is installed.
            $iterator = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator(
                    $base,
                    \FilesystemIterator::SKIP_DOTS | \FilesystemIterator::FOLLOW_SYMLINKS,
                ),
                \RecursiveIteratorIterator::LEAVES_ONLY,
            );

            foreach ($iterator as $file) {
                if ($file instanceof \SplFileInfo && $file->getExtension() === 'php') {
                    yield $file->getPathname() => $dir . '/' . ltrim(substr($file->getPathname(), strlen($base)), '/');
                }
            }
        }
    }

    /**
     * @param list<array<string, mixed>>                       $attributes
     * @param array<string, array{file: string, snippet: string}> $usages
     */
    private function attributePage(string $package, array $attributes, array $usages): string
    {
        $out = $this->header(
            $package . ' attributes',
            sprintf(
                'Every attribute declared by `%s`, with the signature the code has and a usage quoted from the codebase.',
                $package,
            ),
            'attributes-' . $this->slug($package),
            20,
        );

        foreach ($attributes as $attribute) {
            $name = (string) $attribute['name'];
            $out .= sprintf("## `#[%s]`\n\n", $name);
            $out .= sprintf("`%s`\n\n", $attribute['fqcn']);

            $targets = implode(', ', (array) ($attribute['targets'] ?? []));
            $out .= sprintf(
                "Applies to: %s%s\n\n",
                $targets === '' ? 'anything' : $targets,
                ($attribute['repeatable'] ?? false) ? '. Repeatable.' : '',
            );

            $parameters = (array) ($attribute['parameters'] ?? []);
            if ($parameters !== []) {
                $out .= "| parameter | type | required |\n|---|---|---|\n";
                foreach ($parameters as $parameter) {
                    $out .= sprintf(
                        "| `%s` | `%s` | %s |\n",
                        $parameter['name'],
                        $parameter['type'],
                        ($parameter['optional'] ?? false) ? 'no' : 'yes',
                    );
                }

                $out .= "\n";
            } else {
                $out .= "Takes no arguments.\n\n";
            }

            if (isset($usages[$name])) {
                $out .= sprintf("```php\n%s\n```\n\n", $usages[$name]['snippet']);
                $out .= sprintf("— `%s`\n\n", $usages[$name]['file']);
            } else {
                $out .= "_No usage found in this installation._\n\n";
            }
        }

        return $out;
    }

    /**
     * @param list<array<string, mixed>> $commands
     */
    private function commandPage(string $namespace, array $commands): string
    {
        $out = $this->header(
            $namespace . ' commands',
            sprintf(
                'Every `%s` command, with the arguments and options the console actually defines.',
                $namespace,
            ),
            'commands-' . $this->slug($namespace),
            30,
        );

        foreach ($commands as $command) {
            $out .= sprintf("## `%s`\n\n", $command['name']);

            $description = trim((string) ($command['description'] ?? ''));
            if ($description !== '') {
                $out .= $description . "\n\n";
            }

            if (($command['kind'] ?? '') === 'shell') {
                $out .= "Handled by the `bin/semitexa` wrapper before PHP starts.\n\n";
                continue;
            }

            $arguments = (array) ($command['arguments'] ?? []);
            $options = (array) ($command['options'] ?? []);

            $usage = 'bin/semitexa ' . $command['name'];
            foreach ($arguments as $argument) {
                $usage .= ($argument['required'] ?? false)
                    ? ' <' . $argument['name'] . '>'
                    : ' [' . $argument['name'] . ']';
            }

            $out .= sprintf("```bash\n%s\n```\n\n", $usage);

            $documented = array_values(array_filter(
                $options,
                static fn (array $option): bool => !in_array($option['name'], [
                    '--help', '--silent', '--quiet', '--version', '--ansi', '--no-ansi',
                    '--no-interaction', '--verbose',
                ], true),
            ));

            if ($documented !== []) {
                $out .= "| option | takes a value |\n|---|---|\n";
                foreach ($documented as $option) {
                    $out .= sprintf("| `%s` | %s |\n", $option['name'], ($option['accepts_value'] ?? false) ? 'yes' : 'no');
                }

                $out .= "\n";
            }
        }

        return $out;
    }

    /**
     * @param list<array<string, mixed>> $events
     */
    private function eventPage(array $events): string
    {
        $out = $this->header(
            'Events',
            'Every event the runtime routes, named by the listeners that subscribe to it.',
            'events',
            40,
        );

        foreach ($events as $event) {
            $out .= sprintf("## `%s`\n\n", $event['event']);
            $out .= "Listeners:\n\n";
            foreach ((array) ($event['listeners'] ?? []) as $listener) {
                $out .= sprintf("- `%s`\n", $listener);
            }

            $out .= "\n";
        }

        return $out;
    }

    /**
     * @param array<string, string> $files
     * @param array<string, mixed>  $index
     */
    private function indexPage(array $files, array $index): string
    {
        $out = $this->header(
            'Reference',
            'What each part of the public surface is, generated from the code itself.',
            'README',
            10,
        );

        $out .= sprintf(
            "This installation exposes %d attributes, %d commands and %d events.\n\n",
            count((array) ($index['attributes'] ?? [])),
            count((array) ($index['commands'] ?? [])),
            count((array) ($index['events'] ?? [])),
        );

        $out .= "Reference says what a thing is. For when you would want it, see the guides under `en/`.\n\n";

        foreach (['attributes' => 'Attributes', 'commands' => 'Commands'] as $prefix => $heading) {
            $out .= sprintf("## %s\n\n", $heading);
            foreach (array_keys($files) as $path) {
                if (!str_starts_with($path, 'reference/' . $prefix . '-')) {
                    continue;
                }

                $name = basename($path, '.md');
                $out .= sprintf("- [%s](%s.md)\n", substr($name, strlen($prefix) + 1), $name);
            }

            $out .= "\n";
        }

        if (isset($files['reference/events.md'])) {
            $out .= "## Events\n\n- [events](events.md)\n\n";
        }

        return $out;
    }

    /**
     * Pages under `en/` are a structured corpus, not loose markdown: the
     * repository refuses a document without front matter, and the manifest is
     * built from it. Generated pages carry the same schema as hand-written
     * ones — a reader browsing the site should not be able to tell which is
     * which by how it is filed.
     */
    private function header(string $title, string $summary, string $slug, int $order): string
    {
        $frontMatter = implode("\n", [
            '---',
            'id: reference/' . $slug,
            'section: reference',
            'slug: ' . $slug,
            'title: ' . $title,
            'summary: ' . $this->escapeYaml($summary),
            'order: ' . $order,
            'locale: en',
            'status: published',
            '---',
        ]);

        return sprintf("%s\n\n<!-- %s -->\n\n# %s\n\n%s\n\n", $frontMatter, self::PROVENANCE, $title, $summary);
    }

    private function escapeYaml(string $value): string
    {
        return str_contains($value, ':') ? '"' . str_replace('"', '\\"', $value) . '"' : $value;
    }

    private function slug(string $value): string
    {
        $slug = strtolower((string) preg_replace('/[^A-Za-z0-9]+/', '-', $value));

        return trim($slug, '-') ?: 'other';
    }
}
