<?php

declare(strict_types=1);

namespace Semitexa\Docs\Tests\Integration;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\Docs\Application\Service\ReferenceGenerator;

/**
 * The generated half of the documentation is only worth having if it cannot
 * quietly say something untrue, so these cover the two ways it could: an
 * example that does not parse, and a claim of coverage where there is none.
 */
final class ReferenceGeneratorTest extends TestCase
{
    #[Test]
    public function an_attribute_page_carries_the_signature_the_code_has(): void
    {
        $files = (new ReferenceGenerator())->generate($this->index());
        $page = $files['reference/attributes-core.md'] ?? '';

        self::assertStringContainsString('## `#[AsPublicPayload]`', $page);
        self::assertStringContainsString('| `path` | `string` | no |', $page);
        self::assertStringContainsString('Applies to: class', $page);
    }

    #[Test]
    public function an_attribute_with_no_usage_says_so_rather_than_showing_nothing(): void
    {
        // Silence would read as "this needs no example". Twenty-six attributes
        // in this installation are used nowhere, and a reader should know.
        $files = (new ReferenceGenerator())->generate($this->index());

        self::assertStringContainsString('_No usage found in this installation._', $files['reference/attributes-core.md']);
    }

    #[Test]
    public function generated_pages_declare_that_they_are_generated(): void
    {
        foreach ((new ReferenceGenerator())->generate($this->index()) as $path => $contents) {
            self::assertStringStartsWith('---', $contents, $path . ' must carry corpus front matter');
            self::assertStringContainsString('<!-- Generated by', $contents, $path . ' must say it is generated');
        }
    }

    #[Test]
    public function a_command_page_shows_the_arguments_the_console_defines(): void
    {
        $files = (new ReferenceGenerator())->generate($this->index());

        self::assertStringContainsString('bin/semitexa docs:get <document-id>', $files['reference/commands-docs.md']);
    }

    /**
     * @return array<string, mixed>
     */
    private function index(): array
    {
        return [
            'attributes' => [
                [
                    'name' => 'AsPublicPayload',
                    'fqcn' => 'Semitexa\\Core\\Attribute\\AsPublicPayload',
                    'targets' => ['class'],
                    'repeatable' => false,
                    'parameters' => [['name' => 'path', 'type' => 'string', 'optional' => true]],
                ],
                [
                    'name' => 'AsNeverUsedAnywhere',
                    'fqcn' => 'Semitexa\\Core\\Attribute\\AsNeverUsedAnywhere',
                    'targets' => ['class'],
                    'repeatable' => false,
                    'parameters' => [],
                ],
            ],
            'commands' => [[
                'name' => 'docs:get',
                'kind' => 'console',
                'description' => 'Get a document',
                'arguments' => [['name' => 'document-id', 'required' => true]],
                'options' => [['name' => '--format', 'accepts_value' => true]],
            ]],
            'events' => [],
        ];
    }
}
