<?php

declare(strict_types=1);

namespace Semitexa\Docs\Tests\Integration;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;
use Semitexa\Docs\Application\Service\ReferenceGenerator;

/**
 * The generated half of the documentation is only worth having if it cannot
 * quietly say something untrue, so these cover the two ways it could: an
 * example that does not parse, and a claim of coverage where there is none.
 */
final class ReferenceGeneratorTest extends TestCase
{
    #[Test]
    public function an_attribute_page_carries_the_signature_the_code_has(): void
    {
        $files = (new ReferenceGenerator())->generate($this->index());
        $page = $files['reference/attributes-core.md'] ?? '';

        self::assertStringContainsString('## `#[AsPublicPayload]`', $page);
        self::assertStringContainsString('| `path` | `string` | no |', $page);
        self::assertStringContainsString('Applies to: class', $page);
    }

    #[Test]
    public function an_attribute_with_no_usage_says_so_rather_than_showing_nothing(): void
    {
        // Silence would read as "this needs no example". Twenty-six attributes
        // in this installation are used nowhere, and a reader should know.
        $files = (new ReferenceGenerator())->generate($this->index());

        self::assertStringContainsString('_No usage found in this installation._', $files['reference/attributes-core.md']);
    }

    #[Test]
    public function generated_pages_declare_that_they_are_generated(): void
    {
        foreach ((new ReferenceGenerator())->generate($this->index()) as $path => $contents) {
            self::assertStringStartsWith('---', $contents, $path . ' must carry corpus front matter');
            self::assertStringContainsString('<!-- Generated by', $contents, $path . ' must say it is generated');
            self::assertStringContainsString('verified_against: 2026.09.19.1020', $contents, $path . ' must carry release provenance');
        }
    }

    #[Test]
    public function a_new_release_alone_does_not_make_a_page_stale(): void
    {
        // Every release moved the stamp on every page, --check called all of
        // them stale, and ai:verify was red on an untouched tree.
        $generator = new ReferenceGenerator();
        $page = $generator->generate($this->index())['reference/attributes-core.md'];
        $olderStamp = str_replace('verified_against: 2026.09.19.1020', 'verified_against: 2026.09.01.0900', $page);

        self::assertSame($olderStamp, $generator->preserveStamp($page, $olderStamp));
    }

    #[Test]
    public function a_stamp_the_corpus_could_not_have_written_is_not_kept(): void
    {
        // docs:lint skips generated pages, so nothing else would catch these.
        $generator = new ReferenceGenerator();
        $page = $generator->generate($this->index())['reference/attributes-core.md'];

        foreach (['invalid', '2099.01.01.0000'] as $stamp) {
            $onDisk = str_replace('verified_against: 2026.09.19.1020', 'verified_against: ' . $stamp, $page);
            self::assertSame($page, $generator->preserveStamp($page, $onDisk), "stamp '{$stamp}' must be replaced");
        }
    }

    #[Test]
    public function without_a_known_release_a_future_stamp_is_still_replaced(): void
    {
        $index = ['release_version' => null] + $this->index();
        $generator = new ReferenceGenerator();
        $page = $generator->generate($index)['reference/attributes-core.md'];
        self::assertStringContainsString('verified_against: unverified', $page);

        $future = str_replace('verified_against: unverified', 'verified_against: 2099.01.01.0000', $page);
        $past = str_replace('verified_against: unverified', 'verified_against: 2026.09.01.0900', $page);

        self::assertSame($page, $generator->preserveStamp($page, $future));
        self::assertSame($past, $generator->preserveStamp($page, $past));
    }

    #[Test]
    public function a_page_whose_content_moved_takes_the_new_stamp(): void
    {
        $generator = new ReferenceGenerator();
        $page = $generator->generate($this->index())['reference/attributes-core.md'];
        $stale = str_replace(
            ['verified_against: 2026.09.19.1020', '| `path` | `string` | no |'],
            ['verified_against: 2026.09.01.0900', '| `path` | `int` | no |'],
            $page,
        );

        self::assertSame($page, $generator->preserveStamp($page, $stale));
        self::assertSame($page, $generator->preserveStamp($page, null));
    }

    #[Test]
    public function a_command_page_shows_the_arguments_the_console_defines(): void
    {
        $files = (new ReferenceGenerator())->generate($this->index());

        // Quoted, because a reader copies this line and some commands take a prose argument:
        // an unquoted <task> becomes three arguments the moment it contains spaces.
        self::assertStringContainsString('bin/semitexa docs:get "<document-id>"', $files['reference/commands-docs.md']);
    }

    /**
     * @return array<string, mixed>
     */
    private function index(): array
    {
        return [
            'release_version' => '2026.09.19.1020',
            'attributes' => [
                [
                    'name' => 'AsPublicPayload',
                    'fqcn' => 'Semitexa\\Core\\Attribute\\AsPublicPayload',
                    'targets' => ['class'],
                    'repeatable' => false,
                    'parameters' => [['name' => 'path', 'type' => 'string', 'optional' => true]],
                ],
                [
                    'name' => 'AsNeverUsedAnywhere',
                    'fqcn' => 'Semitexa\\Core\\Attribute\\AsNeverUsedAnywhere',
                    'targets' => ['class'],
                    'repeatable' => false,
                    'parameters' => [],
                ],
            ],
            'commands' => [[
                'name' => 'docs:get',
                'kind' => 'console',
                'description' => 'Get a document',
                'arguments' => [['name' => 'document-id', 'required' => true]],
                'options' => [['name' => '--format', 'accepts_value' => true]],
            ]],
            'events' => [],
        ];
    }
}
